name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: az acr login --name rehanacr

      - name: Build and Push Docker image to ACR
        run: |
          docker build -t rehanacr.azurecr.io/churn-fastapi-full:latest .
          docker push rehanacr.azurecr.io/churn-fastapi-full:latest

      - name: Restart Azure Web App
        run: |
          az webapp restart --name churn-fastapi-app --resource-group mlops-rg
